### PR TITLE
update import to work with django < 4.2

### PR DESCRIPTION
**Pull request by stefano-esubasta**
trying to run tests with django versions < 4.2 threw an import error since assertQuerySetEqual was named assertQuerysetEqual, with a lowercase "s" in "set":
```
tests/test_webservices.py:12: in <module>
    from pytest_django.asserts import assertQuerySetEqual
E   ImportError: cannot import name 'assertQuerySetEqual' from 'pytest_django.asserts'
```
this swaps the right name in according to django's version.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Good catch, thanks. I'll make sure CI runs Django 4.2 as well.
